# ReAct Agent Template
name: react_template
version: 0.0.1
type: react
description: A react agent capable of code interpreter
module_name: infiagent.agent.react
class_name: AsyncReactAgent
target_tasks:
  - code interpreter
llm:
  model_name: facebook/opt-125m
  module_name: infiagent.llm
  class_name: OptOpenAIClient
  params:
    temperature: 0.0
    top_p: 0.9
    repetition_penalty: 1.0
    max_tokens: 1024
prompt_template: !prompt ZeroShotReactPrompt
plugins:
  - name: python_code_sandbox
    type: tool
    config: configs/tool_configs/async_python_code_sandbox.yaml